sonar.projectKey=galindogamerbr_galindogamerbr-portal
sonar.organization=galindogamerbr

sonar.sources=src,functions,workers/social-stats-cron/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx
